apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi
          requests:
            cpu: 250m
            ephemeral-storage: 1Gi
            memory: 512Mi      
        image: mariadb:10.9.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          protocol: TCP
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: MARIADB_ROOT_PASSWORD
        volumeMounts:
        - name: config
          mountPath: /docker-entrypoint-initdb.d/YOUR_SQL_SCRIPT.sql
          subPath: freeradius-server.sql
        - mountPath: /var/lib/mysql
          name: mariadb-pv                              
      volumes:
      - name: config
        configMap:
          name: mariadb
      - name: mariadb-pv
        persistentVolumeClaim:
          claimName: mariadb-pvc
        volumeMounts:
      securityContext:
        fsGroup: 1000
             
