apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: default
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mariadb
  type: NodePort