apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: viewer         
  selector:
    app: adminer
  type: NodePort